"""Initial memory layer schema

Revision ID: 8319d9b07eda
Revises: 
Create Date: 2026-06-03 12:13:14.031576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8319d9b07eda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('agent_response', sa.String(), nullable=False),
    sa.Column('sources_used', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('conversation_type', sa.String(), nullable=True),
    sa.Column('compression_status', sa.Boolean(), nullable=True),
    sa.Column('compressed_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('decisions_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('decision_question', sa.String(), nullable=False),
    sa.Column('recommendation_given', sa.String(), nullable=False),
    sa.Column('decision_taken', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_log_id'), 'decisions_log', ['id'], unique=False)
    op.create_table('pivots_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('pivot_suggested', sa.String(), nullable=False),
    sa.Column('pivot_context', sa.String(), nullable=False),
    sa.Column('pivot_taken', sa.Boolean(), nullable=True),
    sa.Column('reason_if_not_taken', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pivots_log_id'), 'pivots_log', ['id'], unique=False)
    op.create_table('startup_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_context_field_name'), 'startup_context', ['field_name'], unique=True)
    op.create_index(op.f('ix_startup_context_id'), 'startup_context', ['id'], unique=False)
    op.create_table('cost_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_tracker_id'), 'cost_tracker', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_tracker_id'), table_name='cost_tracker')
    op.drop_table('cost_tracker')
    op.drop_index(op.f('ix_startup_context_id'), table_name='startup_context')
    op.drop_index(op.f('ix_startup_context_field_name'), table_name='startup_context')
    op.drop_table('startup_context')
    op.drop_index(op.f('ix_pivots_log_id'), table_name='pivots_log')
    op.drop_table('pivots_log')
    op.drop_index(op.f('ix_decisions_log_id'), table_name='decisions_log')
    op.drop_table('decisions_log')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
